// =============================================================================
// Zephyr Test Case : SCRUM-T238
// Title            : Verify UI feedback messages are correct for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : ui, usability, feedback, use-case, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin. Navigate to Employee Creation in OrangeHRM form.
//   2. [When] [Positive] Complete a successful Employee Creation in OrangeHRM with valid data (First Name: &quot;UITest&quot;, Last Name: &quot;User&quot;).
//   3. [Then] Verify the success toast / notification appears and reads &quot;Successfully Saved&quot; (or equivalent).
//   4. [Then] Verify the success message is visible for the expected duration, then disappears or has a dismiss option.
//   5. [Then] Verify the success message is free from spelling mistakes and grammatical errors.
//   6. [When] [Negative] Submit the form with empty required fields.
//   7. [Then] Verify field-level error messages appear in red / highlighted styling.
//   8. [Then] Verify error messages are actionable (e.g. &quot;First Name is required&quot; not just &quot;Error&quot;).
//   9. [When] [Recovery] Fill valid data after seeing errors and re-submit.
//   10. [Then] Verify the form recovers cleanly, error messages clear, and success is shown.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T238 | Verify UI feedback messages are correct for Employee Creation in OrangeHRM', () => {

  test('Verify UI feedback messages are correct for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Submit valid employee to trigger success feedback', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'UIFeedback', lastName: 'Success' });
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails/, { timeout: 15000 });
    });

    await sh.step('Verify success state — Personal Details page is visible', async () => {
      await expect(page.locator('h6.oxd-text').first()).toBeVisible();
    });

    await sh.step('Submit empty form to trigger validation error feedback', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.firstNameInput.clear();
      await addEmployeePage.lastNameInput.clear();
      await addEmployeePage.save();
    });

    await sh.step('Verify validation error messages are visible', async () => {
      await expect(addEmployeePage.validationErrors.first()).toBeVisible({ timeout: 5000 });
    });
  });

});
