// =============================================================================
// Zephyr Test Case : SCRUM-T225
// Title            : Verify concurrent access handling for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : edge-case, error-guessing, dynamic-generated, concurrency, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] Open two separate browser sessions, both logged in as different users.
//   2. [When] In browser 1: navigate to the Employee Creation in OrangeHRM form and fill in all required fields.
//   3. [When] In browser 2: navigate to the same Employee Creation in OrangeHRM form and fill in all required fields with different data.
//   4. [When] Submit both forms as close to simultaneously as possible.
//   5. [Then] Verify no server errors (500), crashes, or data corruption occur.
//   6. [Then] Verify both records are created correctly with their respective data, or one receives a meaningful conflict error.
//   7. [Then] Check the database / list view to ensure no duplicate or merged records exist.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T225 | Verify concurrent access handling for Employee Creation in OrangeHRM', () => {

  test('Verify concurrent access handling for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step("1. [Given] [Pre-condition] Open two separate browser sessions, both logged in as different users.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("2. [When] In browser 1: navigate to the Employee Creation in OrangeHRM form and fill in all required fields.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("3. [When] In browser 2: navigate to the same Employee Creation in OrangeHRM form and fill in all required fields with different data.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("4. [When] Submit both forms as close to simultaneously as possible.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("5. [Then] Verify no server errors (500), crashes, or data corruption occur.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("6. [Then] Verify both records are created correctly with their respective data, or one receives a meaningful conflict error.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("7. [Then] Check the database / list view to ensure no duplicate or merged records exist.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify no error condition after all steps', async () => {
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
