// =============================================================================
// Zephyr Test Case : SCRUM-T236
// Title            : Verify role-based access control for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : security, authorization, rbac, decision-table, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] Identify all roles relevant to Employee Creation in OrangeHRM (Admin, ESS User, Supervisor).
//   2. [Then] Log in as a user with the Admin role. Attempt to perform Employee Creation in OrangeHRM. Verify the action succeeds.
//   3. [When] Log out. Log in as an ESS User (no admin rights). Navigate to Employee Creation in OrangeHRM page.
//   4. [Then] Verify the action is blocked &mdash; either the URL redirects, the button is disabled, or an &quot;Access Denied&quot; message shows.
//   5. [Then] Log out. Log in as a Supervisor role. Attempt the same action. Verify blocked as per role matrix.
//   6. [Then] Access the URL directly without being logged in &mdash; verify redirect to login page.
//   7. [Then] [Post-condition] Confirm no unauthorised actions were recorded in the system audit log.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T236 | Verify role-based access control for Employee Creation in OrangeHRM', () => {

  test('Verify role-based access control for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as Admin and access Employee List', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
      await page.goto('/web/index.php/pim/viewEmployeeList');
      await expect(page).toHaveURL(/viewEmployeeList/, { timeout: 15000 });
      await expect(page.locator('.oxd-table')).toBeVisible();
    });

    await sh.step('Verify Admin can access Add Employee form', async () => {
      await page.goto('/web/index.php/pim/addEmployee');
      await expect(page).toHaveURL(/addEmployee/);
      await expect(page.locator('input[name="firstName"]')).toBeVisible();
    });

    await sh.step('Clear session cookies to simulate unauthenticated user', async () => {
      await page.context().clearCookies();
    });

    await sh.step('Verify unauthenticated access to PIM redirects to Login', async () => {
      await page.goto('/web/index.php/pim/addEmployee');
      await expect(page).toHaveURL(/auth\/login/, { timeout: 10000 });
      await expect(page.locator('input[name="username"]')).toBeVisible();
    });
  });

});
