// =============================================================================
// Zephyr Test Case : SCRUM-T237
// Title            : Verify system resilience under slow network for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : performance, error-guessing, dynamic-generated, network-resilience, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in. Navigate to Employee Creation in OrangeHRM form. Open browser DevTools and throttle network to Slow 3G.
//   2. [When] Fill in all required fields and click Submit.
//   3. [Then] Verify a loading indicator (spinner, disabled button) appears during the request.
//   4. [Then] Verify the submit button is disabled to prevent double-click submission.
//   5. [Then] Wait for the response &mdash; verify it either succeeds or shows a timeout/error message.
//   6. [Then] Reset network to normal. Verify only one record was created (no duplicates from retry).
//   7. [Then] [Edge case] Disconnect network mid-submission and verify the system shows an appropriate offline/error message.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T237 | Verify system resilience under slow network for Employee Creation in OrangeHRM', () => {

  test('Verify system resilience under slow network for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step("1. [Given] [Pre-condition] User is logged in. Navigate to Employee Creation in OrangeHRM form. Open browser DevTools and throttle network to Slow 3G.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("2. [When] Fill in all required fields and click Submit.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("3. [Then] Verify a loading indicator (spinner, disabled button) appears during the request.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("4. [Then] Verify the submit button is disabled to prevent double-click submission.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("5. [Then] Wait for the response &mdash; verify it either succeeds or shows a timeout/error message.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("6. [Then] Reset network to normal. Verify only one record was created (no duplicates from retry).", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("7. [Then] [Edge case] Disconnect network mid-submission and verify the system shows an appropriate offline/error message.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify no error condition after all steps', async () => {
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
