// =============================================================================
// Zephyr Test Case : SCRUM-T230
// Title            : Verify Employee Creation in OrangeHRM rejects invalid input data
// Priority         : Normal
// Labels           : validation, negative, invalid-data, ep-invalid, security-eg, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin. Navigate to Employee Creation in OrangeHRM form.
//   2. [When] Enter numeric-only value &quot;12345&quot; in the First Name field.
//   3. [When] Enter special characters &quot;!@#$%^&amp;*&quot; in the Last Name field.
//   4. [When] Click Save / Submit and observe any validation errors shown.
//   5. [When] Clear the fields and enter HTML injection attempt &quot;&quot; in First Name.
//   6. [Then] Click Save / Submit and verify the system handles this without executing script.
//   7. [When] Clear the fields and enter a value with spaces &quot;John Doe Smith&quot; in a username-type field.
//   8. [Then] Submit and observe system response (expect validation error or sanitised output).
//   9. [Then] Verify no system crash, 500 error, or unhandled exception occurs at any point.
//   10. [Then] [Post-condition] Confirm no invalid records were persisted in the database.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T230 | Verify Employee Creation in OrangeHRM rejects invalid input data', () => {

  test('Verify Employee Creation in OrangeHRM rejects invalid input data', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in and open Add Employee form', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
      await addEmployeePage.navigate();
    });

    await sh.step('Enter invalid data — numerics and symbols in name fields', async () => {
      await addEmployeePage.fillEmployee({ firstName: '12345', lastName: '!@#$%' });
    });

    await sh.step('Submit the form with invalid data', async () => {
      await addEmployeePage.save();
    });

    await sh.step('Verify no crash — system shows validation or stays on form', async () => {
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
