// =============================================================================
// Zephyr Test Case : SCRUM-T224
// Title            : Verify session timeout and re-authentication for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : security, state-transition, session, dynamic-generated, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin. Note the current time.
//   2. [When] Leave the application idle without any interaction for the configured session timeout period.
//   3. [When] After the timeout period, attempt to navigate to a protected page or perform an action.
//   4. [Then] Verify the system redirects to the login page or shows a &quot;Session Expired&quot; message.
//   5. [Then] Log in again with valid credentials and verify the session resumes cleanly.
//   6. [Then] Verify no partial actions were committed during the expired session.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T224 | Verify session timeout and re-authentication for Employee Creation in OrangeHRM', () => {

  test('Verify session timeout and re-authentication for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step("1. [Given] [Pre-condition] User is logged in as Admin. Note the current time.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("2. [When] Leave the application idle without any interaction for the configured session timeout period.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("3. [When] After the timeout period, attempt to navigate to a protected page or perform an action.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("4. [Then] Verify the system redirects to the login page or shows a &quot;Session Expired&quot; message.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("5. [Then] Log in again with valid credentials and verify the session resumes cleanly.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("6. [Then] Verify no partial actions were committed during the expired session.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify no error condition after all steps', async () => {
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
