// =============================================================================
// Zephyr Test Case : SCRUM-T234
// Title            : Verify data is persisted correctly after Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : data-integrity, persistence, regression, state-transition, scrum-5
// Steps from Zephyr:
//   1. [Given] [State: Pre-action] Count existing records before test (note the total).
//   2. [Then] Navigate to Employee Creation in OrangeHRM form. Enter First Name: &quot;PersistTest&quot;, Middle Name: &quot;Verify&quot;, Last Name: &quot;DataCheck&quot;.
//   3. [Then] Click Save. Verify success message appears.
//   4. [And] [State: Record Created] Note the assigned employee ID or unique identifier.
//   5. [And] Navigate away from the page to the employee list/dashboard.
//   6. [When] [State: Navigated Away] Return to the employee list and search for &quot;PersistTest&quot;.
//   7. [When] Open the newly created record.
//   8. [Then] [State: Retrieved] Verify First Name = &quot;PersistTest&quot; (exact match, including case).
//   9. [Then] Verify Middle Name = &quot;Verify&quot; (exact match).
//   10. [Then] Verify Last Name = &quot;DataCheck&quot; (exact match).
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T234 | Verify data is persisted correctly after Employee Creation in OrangeHRM', () => {

  test('Verify data is persisted correctly after Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee and fill with known values', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'Persist', lastName: `DC${uniqueSuffix}` });
      await addEmployeePage.setEmployeeId(`DP${uniqueSuffix}`);
    });

    await sh.step('Save the employee record', async () => {
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails/, { timeout: 20000 });
    });

    await sh.step('Verify First Name is persisted correctly', async () => {
      await expect(page.locator('input[name="firstName"]'))
        .toHaveValue('Persist', { timeout: 8000 });
    });

    await sh.step('Verify Last Name is persisted correctly', async () => {
      await expect(page.locator('input[name="lastName"]'))
        .toHaveValue(`DC${uniqueSuffix}`, { timeout: 8000 });
    });
  });

});
