// =============================================================================
// Zephyr Test Case : SCRUM-T232
// Title            : Verify Employee Creation in OrangeHRM handles special characters and unicode
// Priority         : Normal
// Labels           : edge-case, special-characters, unicode, error-guessing, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin. Navigate to Employee Creation in OrangeHRM form.
//   2. [Then] Enter First Name: &quot;Jos&eacute;&quot; (unicode accented character). Submit and verify acceptance and correct storage/display.
//   3. [Then] Navigate back. Enter First Name: &quot;O'Brien&quot; (apostrophe). Submit and verify no SQL error occurs and data is stored correctly.
//   4. [Then] Navigate back. Enter Last Name: &quot;M&uuml;ller&quot; (umlaut). Submit and verify the umlaut is preserved in the saved record.
//   5. [When] Navigate back. Enter First Name: &quot;王&quot; (CJK character). Submit and observe system handling (accept or graceful reject).
//   6. [Then] For any accepted values: navigate to the employee profile and verify the displayed name matches exactly what was entered.
//   7. [Then] Verify no JavaScript errors, 500 errors, or database exceptions occur at any step.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T232 | Verify Employee Creation in OrangeHRM handles special characters and unicode', () => {

  test('Verify Employee Creation in OrangeHRM handles special characters and unicode', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step("Test unicode and accented characters (Müller, O'Brien)", async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'Müller', lastName: "O'Brien" });
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });

    await sh.step('Test symbol characters in name fields (Test@User, Hash#Name)', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'Test@User', lastName: 'Hash#Name' });
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
