// =============================================================================
// Zephyr Test Case : SCRUM-T228
// Title            : Verify successful Employee Creation in OrangeHRM with valid inputs
// Priority         : Normal
// Labels           : happy-path, smoke, ep-valid, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged out. Browser is open at the application URL.
//   2. [Given] Navigate to the application login page and log in with valid admin credentials (Username: Admin, Password: admin123).
//   3. [When] Navigate to the Employee Creation in OrangeHRM page or form via the main navigation menu.
//   4. [Then] Verify the form/page loads completely with all fields visible.
//   5. [When] Fill in First Name field with valid test data: &quot;AutoTest&quot; (alphabetic, within 1&ndash;50 char limit).
//   6. [When] Fill in Last Name field with valid test data: &quot;Employee&quot; (alphabetic, within 1&ndash;50 char limit).
//   7. [When] Fill in any other required fields with valid test data as per test data table.
//   8. [When] Click the Save / Submit button to trigger the action.
//   9. [And] Wait for the system response (success message or redirect).
//   10. [Then] Verify a success confirmation message is displayed (e.g. &quot;Successfully Saved&quot;).
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T228 | Verify successful Employee Creation in OrangeHRM with valid inputs', () => {

  test('Verify successful Employee Creation in OrangeHRM with valid inputs', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Open Login Page', async () => {
      await loginPage.goto();
    });

    await sh.step('Enter credentials and log in as HR Admin', async () => {
      await loginPage.usernameInput.fill(CREDENTIALS.admin.username);
      await loginPage.passwordInput.fill(CREDENTIALS.admin.password);
      await loginPage.loginButton.click();
      await page.waitForURL('**/dashboard**', { timeout: 15000 });
    });

    await sh.step('Navigate to PIM — Add Employee form', async () => {
      await addEmployeePage.navigate();
      await expect(page).toHaveURL(/addEmployee/);
    });

    await sh.step('Fill all required fields with valid data', async () => {
      await addEmployeePage.fillEmployee({
        firstName: TEST_EMPLOYEE.firstName,
        lastName:  TEST_EMPLOYEE.lastName
      });
    });

    await sh.step('Submit form and verify redirect to Personal Details', async () => {
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails/, { timeout: 15000 });
      await expect(page.locator('h6.oxd-text').first()).toBeVisible();
    });
  });

});
