// =============================================================================
// Zephyr Test Case : SCRUM-T229
// Title            : Verify mandatory fields are enforced for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : validation, negative, required-fields, ep-empty, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin.
//   2. [When] Navigate to the Employee Creation in OrangeHRM page or form.
//   3. [When] Leave the First Name field completely empty (do not enter any value).
//   4. [When] Leave the Last Name field completely empty (do not enter any value).
//   5. [And] Leave any other mandatory fields empty.
//   6. [When] Click the Save / Submit button without filling any required fields.
//   7. [And] Observe all inline validation messages that appear below each empty field.
//   8. [Then] Verify the form does NOT submit (URL remains on the form page).
//   9. [Then] Verify the First Name field shows an error message (e.g. &quot;Required&quot;).
//   10. [Then] Verify the Last Name field shows an error message (e.g. &quot;Required&quot;).
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T229 | Verify mandatory fields are enforced for Employee Creation in OrangeHRM', () => {

  test('Verify mandatory fields are enforced for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Open Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step('Clear all required fields (First Name, Last Name)', async () => {
      await addEmployeePage.firstNameInput.clear();
      await addEmployeePage.lastNameInput.clear();
    });

    await sh.step('Attempt to submit with empty required fields', async () => {
      await addEmployeePage.save();
    });

    await sh.step('Verify inline validation error messages appear', async () => {
      await expect(addEmployeePage.validationErrors.first()).toBeVisible({ timeout: 5000 });
      const errorCount = await addEmployeePage.validationErrors.count();
      expect(errorCount).toBeGreaterThanOrEqual(1);
      await expect(page).not.toHaveURL(/viewPersonalDetails/);
    });
  });

});
