// =============================================================================
// Zephyr Test Case : SCRUM-T239
// Title            : Verify keyboard navigation and accessibility for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : usability, use-case, dynamic-generated, accessibility, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in. Navigate to the Employee Creation in OrangeHRM page.
//   2. [When] Without using the mouse, press Tab repeatedly to navigate through all form fields.
//   3. [Then] Verify the tab order follows a logical top-to-bottom, left-to-right sequence.
//   4. [Then] Verify each focused element has a visible focus indicator (outline or highlight).
//   5. [When] Navigate to the Submit/Save button using Tab and press Enter to submit.
//   6. [Then] Verify the form submits successfully via keyboard alone.
//   7. [Then] Trigger a validation error and verify the error message is associated with the field (aria-describedby or similar).
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T239 | Verify keyboard navigation and accessibility for Employee Creation in OrangeHRM', () => {

  test('Verify keyboard navigation and accessibility for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step("1. [Given] [Pre-condition] User is logged in. Navigate to the Employee Creation in OrangeHRM page.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("2. [When] Without using the mouse, press Tab repeatedly to navigate through all form fields.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("3. [Then] Verify the tab order follows a logical top-to-bottom, left-to-right sequence.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("4. [Then] Verify each focused element has a visible focus indicator (outline or highlight).", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("5. [When] Navigate to the Submit/Save button using Tab and press Enter to submit.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("6. [Then] Verify the form submits successfully via keyboard alone.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("7. [Then] Trigger a validation error and verify the error message is associated with the field (aria-describedby or similar).", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify no error condition after all steps', async () => {
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
