// =============================================================================
// Zephyr Test Case : SCRUM-T233
// Title            : Verify cancel or discard action during Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : negative, cancel, data-integrity, state-transition, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin. Navigate to Employee Creation in OrangeHRM form.
//   2. [Then] [State: Form Empty] Verify the form starts in an empty state.
//   3. [When] [State: Partially Filled] Enter First Name: &quot;CancelTest&quot; and Last Name: &quot;Partial&quot; without submitting.
//   4. [When] Without clicking Save, click the Cancel button (or navigate away using the browser Back button).
//   5. [And] [State: Cancelled] Observe what happens &mdash; browser may show an &quot;unsaved changes&quot; warning.
//   6. [Then] If a warning appears, confirm the discard action.
//   7. [Then] [State: Returned] Verify the user is returned to the previous page or employee list.
//   8. [Then] Navigate to the employee list and search for &quot;CancelTest&quot;. Verify no partial record exists.
//   9. [Then] Verify zero data was persisted from the cancelled form entry.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T233 | Verify cancel or discard action during Employee Creation in OrangeHRM', () => {

  test('Verify cancel or discard action during Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee and partially fill the form', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'CancelTest', lastName: 'Discard' });
    });

    await sh.step('Cancel — navigate away without saving', async () => {
      await addEmployeePage.cancel();
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify no redirect to Personal Details occurred', async () => {
      expect(page.url()).not.toMatch(/viewPersonalDetails/);
    });

    await sh.step('Search Employee List — cancelled record should not exist', async () => {
      await employeeListPage.searchEmployee('CancelTest');
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
