// =============================================================================
// Zephyr Test Case : SCRUM-T231
// Title            : Verify boundary values are handled correctly for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : boundary, edge-case, bva, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin. Navigate to Employee Creation in OrangeHRM form.
//   2. [Then] [BVA-1] Enter minimum boundary value: single character &quot;A&quot; in First Name and &quot;B&quot; in Last Name. Submit and verify the form accepts it.
//   3. [Then] [BVA-2] Enter Min+1 boundary value: two characters &quot;AB&quot; in First Name. Submit and verify acceptance.
//   4. [Then] [BVA-3] Navigate back and enter Max-1 boundary value: 49-character string in First Name. Submit and verify acceptance.
//   5. [Then] [BVA-4] Navigate back and enter the exact maximum boundary: 50-character string in First Name. Submit and verify acceptance.
//   6. [Then] [BVA-5] Navigate back and enter Max+1 boundary: 51-character string in First Name. Submit and verify rejection with error message.
//   7. [And] Record actual system behaviour for each boundary point in a table.
//   8. [Then] Verify that accepted boundary values are correctly persisted and displayed.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T231 | Verify boundary values are handled correctly for Employee Creation in OrangeHRM', () => {

  test('Verify boundary values are handled correctly for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Test minimum boundary — single character names (A, B)', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'A', lastName: 'B' });
      await addEmployeePage.save();
      await expect(page).toHaveURL(/viewPersonalDetails|addEmployee/, { timeout: 10000 });
    });

    await sh.step('Test maximum boundary — 50-character names', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({
        firstName: 'A'.repeat(50),
        lastName:  'B'.repeat(50)
      });
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });

    await sh.step('Test over-maximum boundary — 101-character names', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({
        firstName: 'X'.repeat(101),
        lastName:  'Y'.repeat(101)
      });
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
