// =============================================================================
// Zephyr Test Case : SCRUM-T227
// Title            : Verify copy-paste and autofill behaviour for Employee Creation in OrangeHRM
// Priority         : Normal
// Labels           : edge-case, error-guessing, dynamic-generated, clipboard-paste, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in. Navigate to Employee Creation in OrangeHRM form.
//   2. [When] Copy text with leading/trailing spaces from an external source and paste into the First Name field.
//   3. [Then] Verify the system either trims the whitespace or accepts it without breaking validation.
//   4. [And] Copy multi-line text and paste into a single-line field (e.g. Last Name).
//   5. [Then] Verify newline characters are stripped and the field shows clean single-line text.
//   6. [When] Allow or trigger browser autofill for the form fields.
//   7. [Then] Verify autofilled values are recognized by form validation and do not bypass required-field checks.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T227 | Verify copy-paste and autofill behaviour for Employee Creation in OrangeHRM', () => {

  test('Verify copy-paste and autofill behaviour for Employee Creation in OrangeHRM', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Navigate to Add Employee form', async () => {
      await addEmployeePage.navigate();
    });

    await sh.step("1. [Given] [Pre-condition] User is logged in. Navigate to Employee Creation in OrangeHRM form.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("2. [When] Copy text with leading/trailing spaces from an external source and paste into the First Name field.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("3. [Then] Verify the system either trims the whitespace or accepts it without breaking validation.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("4. [And] Copy multi-line text and paste into a single-line field (e.g. Last Name).", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("5. [Then] Verify newline characters are stripped and the field shows clean single-line text.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("6. [When] Allow or trigger browser autofill for the form fields.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step("7. [Then] Verify autofilled values are recognized by form validation and do not bypass required-field checks.", async () => {
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify no error condition after all steps', async () => {
      await page.waitForLoadState('networkidle');
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
