// =============================================================================
// Zephyr Test Case : SCRUM-T223
// Title            : Verify duplicate Employee Creation in OrangeHRM is prevented
// Priority         : Normal
// Labels           : validation, negative, duplicate, error-guessing, scrum-5
// Steps from Zephyr:
//   1. [Given] [Pre-condition] User is logged in as Admin.
//   2. [When] Perform a successful Employee Creation in OrangeHRM: Enter First Name &quot;DupeTest&quot;, Last Name &quot;DupeUser&quot;, save the record.
//   3. [And] Note the generated employee ID or unique identifier: &quot;DUP001&quot;.
//   4. [And] Navigate back to the Employee Creation in OrangeHRM form.
//   5. [When] Attempt to create a second record with the exact same unique identifier &quot;DUP001&quot;.
//   6. [When] Click Save / Submit.
//   7. [When] Observe the system response for the duplicate attempt.
//   8. [Then] Verify a duplicate-specific error message is displayed (e.g. &quot;Employee ID already exists&quot;).
//   9. [Then] Verify only one record exists in the system for the tested identifier.
//   10. [And] [Cleanup] Delete the test record created in step 2 if the system allows.
// =============================================================================
// Generated by  : scripts/generate-playwright.js
// Application   : OrangeHRM — https://opensource-demo.orangehrmlive.com
// Module        : PIM → Add Employee
// Credentials   : Admin / admin123
// Fixtures      : base.fixture.js (POM + ScreenshotHelper)
// =============================================================================
'use strict';
const { test, expect }                = require('../fixtures/base.fixture');
const { CREDENTIALS, TEST_EMPLOYEE } = require('../data/testData');

test.describe('SCRUM-T223 | Verify duplicate Employee Creation in OrangeHRM is prevented', () => {

  test('Verify duplicate Employee Creation in OrangeHRM is prevented', async ({ page, loginPage, addEmployeePage, employeeListPage, sh, uniqueSuffix }, testInfo) => {

    await sh.step('Log in as HR Admin', async () => {
      await loginPage.login(CREDENTIALS.admin.username, CREDENTIALS.admin.password);
    });

    await sh.step('Create first employee with Employee ID DUP-TEST-001', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'DupFirst', lastName: 'DupLast' });
      await addEmployeePage.setEmployeeId('DUP-TEST-001');
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Attempt second creation with same Employee ID DUP-TEST-001', async () => {
      await addEmployeePage.navigate();
      await addEmployeePage.fillEmployee({ firstName: 'DupFirst2', lastName: 'DupLast2' });
      await addEmployeePage.setEmployeeId('DUP-TEST-001');
      await addEmployeePage.save();
      await page.waitForLoadState('networkidle');
    });

    await sh.step('Verify system blocks or warns — no crash on duplicate', async () => {
      expect(page.url()).not.toMatch(/error|exception/i);
    });
  });

});
